### ISSUE TITLE
A release would do fine

### ISSUE THREAD

**Issue by sebastialonso** [gonewandering/angles#72]
I went ahead with what I mentioned in #71 and created a tiny library for custom charts that mixes well with angles. I was going to write the bower dependencies to add angles, but it doesn't have a release. 
That would rock.

**Comment by gonewandering** [comment]
Hey Sebastian, this sounds excellent. Will review and merge this afternoon. - Lindsay

**Comment by sebastialonso** [comment]
Awesome!

**Comment by jmelosegui** [comment]
Why is this closed? I cant see any release here. 
Hopefully when a new release is available you can include #76.
